- name: Shell module example
  hosts: reduncen
  tasks:
  - name: Change ssh port to 2009
  set_fact:
    ansible_port: 2009
  - name: Check system information
    shell:
      "lsb_release -a"
    register: os_info
    
  - debug:
      msg: "{{os_info.stdout_lines}}"
