- name: Shell module example
  hosts: reduncen
  tasks:
  
  - name: Check system information
    shell:
      "lsb_release -a"
    register: os_info
    
  - debug:
      msg: "{{os_info.stdout_lines}}"
