# host usually use all , sometime and apply to some server role
# but also can use ansible-playbook with --limit , more dynamicly
# reference
# https://gist.github.com/gomes/7697353
# http://stackoverflow.com/questions/3510673/find-and-kill-a-process-in-one-line-using-bash-and-regex
# kill $(ps aux | grep '[/]home/testworkspace/qleoffice' | awk '{print $2}')
- hosts: dev
  #sudo permission
  become: true
#  become_method: su


  vars:
    tomcat_folder: apache-tomcat-8.5.54
    tomcat_path: "/usr/local/{{ tomcat_folder }}"
    grep_string: "[/]usr/local/{{ tomcat_folder }}"

  tasks:
    - name: ==> shutdown tomcat ,path = "{{ tomcat_path }}/bin/"
      command: sh {{ tomcat_path }}/bin/shutdown.sh

    - name: ==> sleep 5s
      command: sleep 5s

    - name: Check if Apache is running
      shell: ps aux | grep '{{ grep_string }}' | awk '{print $2}'
      ignore_errors: yes
      changed_when: false
      register: service_apache_status

    - debug: msg="Check if Apache is running {{ service_apache_status }}"
    - debug: msg="service_apache_status.stdout != '' =  {{ service_apache_status.stdout != ''}}"

    - name: kill process is tomcat is still running
      shell: kill $(ps aux | grep '{{ grep_string }}' | awk '{print $2}')
      when: service_apache_status.stdout != ''

    - command: sleep 1s
      when: service_apache_status.stdout != ''

    - name: ==> Clean Memory ,path = "{{ tomcat_path }}/bin/"
      command: sh {{ tomcat_path }}/bin/clearMemory.sh  

    - name: ==> startup tomcat , path = {{ tomcat_path }}/bin/startup.sh
      shell: setsid /bin/sh -i -c "{{ tomcat_path }}/bin/startup.sh"
